// Code generated by counterfeiter. DO NOT EDIT.
package vaultfakes

import (
	"context"
	"sync"

	"github.com/dkyanakiev/vaulty/internal/vault"
	"github.com/hashicorp/vault/api"
)

type FakeKV2 struct {
	GetStub        func(context.Context, string) (*api.KVSecret, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getReturns struct {
		result1 *api.KVSecret
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *api.KVSecret
		result2 error
	}
	GetMetadataStub        func(context.Context, string) (*api.KVMetadata, error)
	getMetadataMutex       sync.RWMutex
	getMetadataArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getMetadataReturns struct {
		result1 *api.KVMetadata
		result2 error
	}
	getMetadataReturnsOnCall map[int]struct {
		result1 *api.KVMetadata
		result2 error
	}
	PatchStub        func(context.Context, string, map[string]interface{}, ...vault.KVOption) (*api.KVSecret, error)
	patchMutex       sync.RWMutex
	patchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 map[string]interface{}
		arg4 []vault.KVOption
	}
	patchReturns struct {
		result1 *api.KVSecret
		result2 error
	}
	patchReturnsOnCall map[int]struct {
		result1 *api.KVSecret
		result2 error
	}
	PutStub        func(context.Context, string, map[string]interface{}, ...vault.KVOption) (*api.KVSecret, error)
	putMutex       sync.RWMutex
	putArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 map[string]interface{}
		arg4 []vault.KVOption
	}
	putReturns struct {
		result1 *api.KVSecret
		result2 error
	}
	putReturnsOnCall map[int]struct {
		result1 *api.KVSecret
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeKV2) Get(arg1 context.Context, arg2 string) (*api.KVSecret, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeKV2) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeKV2) GetCalls(stub func(context.Context, string) (*api.KVSecret, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeKV2) GetArgsForCall(i int) (context.Context, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeKV2) GetReturns(result1 *api.KVSecret, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *api.KVSecret
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) GetReturnsOnCall(i int, result1 *api.KVSecret, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *api.KVSecret
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *api.KVSecret
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) GetMetadata(arg1 context.Context, arg2 string) (*api.KVMetadata, error) {
	fake.getMetadataMutex.Lock()
	ret, specificReturn := fake.getMetadataReturnsOnCall[len(fake.getMetadataArgsForCall)]
	fake.getMetadataArgsForCall = append(fake.getMetadataArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetMetadataStub
	fakeReturns := fake.getMetadataReturns
	fake.recordInvocation("GetMetadata", []interface{}{arg1, arg2})
	fake.getMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeKV2) GetMetadataCallCount() int {
	fake.getMetadataMutex.RLock()
	defer fake.getMetadataMutex.RUnlock()
	return len(fake.getMetadataArgsForCall)
}

func (fake *FakeKV2) GetMetadataCalls(stub func(context.Context, string) (*api.KVMetadata, error)) {
	fake.getMetadataMutex.Lock()
	defer fake.getMetadataMutex.Unlock()
	fake.GetMetadataStub = stub
}

func (fake *FakeKV2) GetMetadataArgsForCall(i int) (context.Context, string) {
	fake.getMetadataMutex.RLock()
	defer fake.getMetadataMutex.RUnlock()
	argsForCall := fake.getMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeKV2) GetMetadataReturns(result1 *api.KVMetadata, result2 error) {
	fake.getMetadataMutex.Lock()
	defer fake.getMetadataMutex.Unlock()
	fake.GetMetadataStub = nil
	fake.getMetadataReturns = struct {
		result1 *api.KVMetadata
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) GetMetadataReturnsOnCall(i int, result1 *api.KVMetadata, result2 error) {
	fake.getMetadataMutex.Lock()
	defer fake.getMetadataMutex.Unlock()
	fake.GetMetadataStub = nil
	if fake.getMetadataReturnsOnCall == nil {
		fake.getMetadataReturnsOnCall = make(map[int]struct {
			result1 *api.KVMetadata
			result2 error
		})
	}
	fake.getMetadataReturnsOnCall[i] = struct {
		result1 *api.KVMetadata
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) Patch(arg1 context.Context, arg2 string, arg3 map[string]interface{}, arg4 ...vault.KVOption) (*api.KVSecret, error) {
	fake.patchMutex.Lock()
	ret, specificReturn := fake.patchReturnsOnCall[len(fake.patchArgsForCall)]
	fake.patchArgsForCall = append(fake.patchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 map[string]interface{}
		arg4 []vault.KVOption
	}{arg1, arg2, arg3, arg4})
	stub := fake.PatchStub
	fakeReturns := fake.patchReturns
	fake.recordInvocation("Patch", []interface{}{arg1, arg2, arg3, arg4})
	fake.patchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeKV2) PatchCallCount() int {
	fake.patchMutex.RLock()
	defer fake.patchMutex.RUnlock()
	return len(fake.patchArgsForCall)
}

func (fake *FakeKV2) PatchCalls(stub func(context.Context, string, map[string]interface{}, ...vault.KVOption) (*api.KVSecret, error)) {
	fake.patchMutex.Lock()
	defer fake.patchMutex.Unlock()
	fake.PatchStub = stub
}

func (fake *FakeKV2) PatchArgsForCall(i int) (context.Context, string, map[string]interface{}, []vault.KVOption) {
	fake.patchMutex.RLock()
	defer fake.patchMutex.RUnlock()
	argsForCall := fake.patchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeKV2) PatchReturns(result1 *api.KVSecret, result2 error) {
	fake.patchMutex.Lock()
	defer fake.patchMutex.Unlock()
	fake.PatchStub = nil
	fake.patchReturns = struct {
		result1 *api.KVSecret
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) PatchReturnsOnCall(i int, result1 *api.KVSecret, result2 error) {
	fake.patchMutex.Lock()
	defer fake.patchMutex.Unlock()
	fake.PatchStub = nil
	if fake.patchReturnsOnCall == nil {
		fake.patchReturnsOnCall = make(map[int]struct {
			result1 *api.KVSecret
			result2 error
		})
	}
	fake.patchReturnsOnCall[i] = struct {
		result1 *api.KVSecret
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) Put(arg1 context.Context, arg2 string, arg3 map[string]interface{}, arg4 ...vault.KVOption) (*api.KVSecret, error) {
	fake.putMutex.Lock()
	ret, specificReturn := fake.putReturnsOnCall[len(fake.putArgsForCall)]
	fake.putArgsForCall = append(fake.putArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 map[string]interface{}
		arg4 []vault.KVOption
	}{arg1, arg2, arg3, arg4})
	stub := fake.PutStub
	fakeReturns := fake.putReturns
	fake.recordInvocation("Put", []interface{}{arg1, arg2, arg3, arg4})
	fake.putMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeKV2) PutCallCount() int {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	return len(fake.putArgsForCall)
}

func (fake *FakeKV2) PutCalls(stub func(context.Context, string, map[string]interface{}, ...vault.KVOption) (*api.KVSecret, error)) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = stub
}

func (fake *FakeKV2) PutArgsForCall(i int) (context.Context, string, map[string]interface{}, []vault.KVOption) {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	argsForCall := fake.putArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeKV2) PutReturns(result1 *api.KVSecret, result2 error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = nil
	fake.putReturns = struct {
		result1 *api.KVSecret
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) PutReturnsOnCall(i int, result1 *api.KVSecret, result2 error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = nil
	if fake.putReturnsOnCall == nil {
		fake.putReturnsOnCall = make(map[int]struct {
			result1 *api.KVSecret
			result2 error
		})
	}
	fake.putReturnsOnCall[i] = struct {
		result1 *api.KVSecret
		result2 error
	}{result1, result2}
}

func (fake *FakeKV2) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.getMetadataMutex.RLock()
	defer fake.getMetadataMutex.RUnlock()
	fake.patchMutex.RLock()
	defer fake.patchMutex.RUnlock()
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeKV2) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vault.KV2 = new(FakeKV2)
